# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wormhole < Formula
  desc "Zero-config tunnel tool to expose local services to the internet"
  homepage "https://github.com/lucientong/wormhole"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/lucientong/wormhole/releases/download/v0.2.0/wormhole_0.2.0_darwin_x86_64.tar.gz"
      sha256 "454619ca84477cc0c907523ca73cbffa0fc0c52da3aa2009f847eb1da9699e1e"

      def install
        bin.install "wormhole"
      end
    end
    on_arm do
      url "https://github.com/lucientong/wormhole/releases/download/v0.2.0/wormhole_0.2.0_darwin_arm64.tar.gz"
      sha256 "14f5c76f7df6fa3f01a0fd88873f69b9ec3f5ad0de7b23a9c41c90cefc0d1e3e"

      def install
        bin.install "wormhole"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lucientong/wormhole/releases/download/v0.2.0/wormhole_0.2.0_linux_x86_64.tar.gz"
        sha256 "0ab622c6bed1fcdaf02ff21bc885abfb28e58938d0f09c9c835f06393f7e356a"

        def install
          bin.install "wormhole"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lucientong/wormhole/releases/download/v0.2.0/wormhole_0.2.0_linux_arm64.tar.gz"
        sha256 "bd41c9dd24b23f81ef8dd77f495285f9728bb7d2ce556550d49790e7bdc7d1b7"

        def install
          bin.install "wormhole"
        end
      end
    end
  end

  test do
    system "#{bin}/wormhole", "version"
  end
end
